version: '3.1'
services:
  web:
    image: odoo:15.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    
    volumes:
      - ./config:/etc/odoo
      - ./custom_addons:/opt/odoo/custom_addons

  #   environment:
  #   - HOST=mydb
  #   - USER=odoo
  #   - PASSWORD=myodoo
  # mydb:
  #   image: postgres:12
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_PASSWORD=myodoo
  #     - POSTGRES_USER=odoo
